// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7sbPMp_TTEllbcrczY9tVssK9fvW2t-A',
    appId: '1:514734174262:web:62fd64c34fc10ad1c7a897',
    messagingSenderId: '514734174262',
    projectId: 'ditonton-app-f1e99',
    authDomain: 'ditonton-app-f1e99.firebaseapp.com',
    storageBucket: 'ditonton-app-f1e99.appspot.com',
    measurementId: 'G-LJ763DF2ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkkkQ6mfL7YLZlU76yMc9UAPG6AW3jP7Q',
    appId: '1:514734174262:android:cccaa87fb38a90a2c7a897',
    messagingSenderId: '514734174262',
    projectId: 'ditonton-app-f1e99',
    storageBucket: 'ditonton-app-f1e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeNFCuVlnvm6GJnT02XNRcF6RcCKDBpR0',
    appId: '1:514734174262:ios:450402296f355d7ec7a897',
    messagingSenderId: '514734174262',
    projectId: 'ditonton-app-f1e99',
    storageBucket: 'ditonton-app-f1e99.appspot.com',
    iosBundleId: 'com.example.ditontonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeNFCuVlnvm6GJnT02XNRcF6RcCKDBpR0',
    appId: '1:514734174262:ios:450402296f355d7ec7a897',
    messagingSenderId: '514734174262',
    projectId: 'ditonton-app-f1e99',
    storageBucket: 'ditonton-app-f1e99.appspot.com',
    iosBundleId: 'com.example.ditontonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7sbPMp_TTEllbcrczY9tVssK9fvW2t-A',
    appId: '1:514734174262:web:17dceadc80bf176ec7a897',
    messagingSenderId: '514734174262',
    projectId: 'ditonton-app-f1e99',
    authDomain: 'ditonton-app-f1e99.firebaseapp.com',
    storageBucket: 'ditonton-app-f1e99.appspot.com',
    measurementId: 'G-LWRZ8RENVV',
  );
}
